spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.97.112.202:3307/test_loan_biz?useUnicode=true&characterEncoding=utf-8
      username: yunche
      password: yc_123
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
      initialSize: 8
      min-idle: 0
      max-idle: 16
      max-active: 20
      test-on-borrow: true

  redis:
    host: 47.97.122.31
    port: 6380
    password: yunche@1234
    timeout: 3000
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 24
        max-wait: 2000

  mail:
    host: smtp.exmail.qq.com
    username: yanzheng@yunchejinrong.com
    password: Yunche@1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jtx:
    jtxServierIP: 183.136.187.207
    jtxUserName: root
    jtxPassword: jtx@1722
    jtxUrl: http://121.41.20.151:7013/assetApi/service
    jtxPort: 22

---

spring:
  profiles: prepub
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uk11f20h4i65u9oo.mysql.rds.aliyuncs.com:3306/yunche_loan_biz?useUnicode=true&characterEncoding=utf-8
      username: yuncheadmin
      password: ycjinfu@2099
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
      initialSize: 8
      min-idle: 0
      max-idle: 8
      max-active: 8
      test-on-borrow: true

  redis:
    host: 47.97.122.31
    port: 6381
    password: yunche@1234
    timeout: 3000
    lettuce:
      pool:
        max-active: 50
        max-idle: 30
        min-idle: 0
        max-wait: 10000

  mail:
    host: smtp.exmail.qq.com
    username: yanzheng@yunchejinrong.com
    password: Yunche@1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jtx:
      jtxServierIP: 120.26.205.193
      jtxUserName: asset
      jtxPassword: asset001
      jtxUrl: http://114.215.191.155:7013/assetApi/service
      jtxPort: 22

---

spring:
  profiles: pub
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uk11f20h4i65u9rw.mysql.rds.aliyuncs.com:3306/yunche_loan_biz?useUnicode=true&characterEncoding=utf-8
      username: yuncheadmin
      password: ycjinfu@2099
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
      initialSize: 16
      minIdle: 16
      max-idle: 16
      max-active: 30
      test-on-borrow: true

  redis:
    host: r-bp1b3d268c17de84.redis.rds.aliyuncs.com
    port: 6379
    password: Yunche2018
    timeout: 3000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 500
        min-idle: 50
        max-wait: 5000

  mail:
    host: smtp.exmail.qq.com
    username: yanzheng@yunchejinrong.com
    password: Yunche@1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jtx:
      jtxServierIP: 120.26.205.193
      jtxUserName: asset
      jtxPassword: asset001
      jtxUrl: http://114.215.191.155:7013/assetApi/service
      jtxPort: 22

