spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.97.112.202:3307/test_loan_biz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: yunche
      password: yc_123
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
      initialSize: 8
      min-idle: 0
      max-active: 20
      test-on-borrow: true

  redis:
    host: 47.97.122.31
    port: 6380
    password: yunche@1234
    timeout: 5000
    lettuce:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 24
        max-wait: 2000

  mail:
    host: smtp.exmail.qq.com
    username: yanzheng@yunchejinrong.com
    password: Yunche@1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jtx:
    jtxServierIP: 183.136.187.207
    jtxUserName: root
    jtxPassword: jtx@1722
    jtxUrl: http://121.41.20.151:7013/assetApi/service
    jtxPort: 22
  finance:
    callBackUrl: http://www.yunchejinrong.com:8090/api/v1/loanorder/finance/remitInfo
    accountingVoucherHost: http://47.96.78.20:8012
    secondCarHost: http://47.97.122.31:8888
    paymentHost: http://47.96.78.20:8019

  estage:
    systemurl: http://hrfax.imwork.net:8998/bank/route
    assurerNo: S18046287
    platNo: yunche
    bankCode: "0180400023"
    productType: 2
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCFZnUVz07wuQfI5kf3uOaaJcpq*W3yQhJnIX2k-EKwKZaSkyuXutk0TXqwT-GXxIQJqmkjLup*HN7H1uF7JMfxl00AnncHB82LqUQKQwf5wcdDTNhvKLQtjRoLE3ry6ARoYHu5AkZPKW7sMM4o*UegPlSr45p4ZsK0iVdjqmgZfwIDAQAB
    signPrivateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAKOoelzwAU5Asw9zknkTYGvfZr0Ap6ZDL6NMSNRYZ2maVJd5xOfSRqTkEq1Ne*h2Qe3wCKdxo0SuCVWNjM-nd3af*fb4YcWdlDuHaA1s28I5hZtVp2sbF*nvgdeUwSz-X0hQGcaqVzcTKDH9l2XuMC**OEofyyosU2jvEIGdwqSNAgMBAAECgYAkojvxvc*tApKSbN5mt82nl-RZbmIYt4VcWmEbF0bevqsc1SccdVdW5a7AmE2aNY6AgnCNesR-RS3Vtr-Ech2tVfwMXypJsXN5hq0uyM6iDkE6kFhGL1zui72u9RQJvdB7CsNfEONIaFlX46MUOdF0fR2n-sGLMc1qzpj*L3k6QQJBAOJfQRF6ehE5d1Sm*7q9uObte1ubako89TSGZmCOk-3vpm9CRTey-18Ids98yMNg3Wy53M4oEzjwjdnnulX9PpUCQQC5E-NySYbigVCsO5Tjr*iAA1ykdGIgaRM45s2tvbMLYQdZYhnkPRjSj*Y7I915cp5klQ75T260InPYQqBkb2gZAkEAjRYtKcWZ*s5EL4B7eCHy8gqlTa0JjAd*FCSH-joexq-snX9CQLrRKtvNoPf28L6YgsE8e0jC4kQbROqGWj2iGQJBAKkXVUCBdL7UrsPs26b6PE1YxPdrbYt29Jz0Ic4ulro6t*AuBMHGIDugRRSbO*mNkrEKjlew-s*M*pIGrUuVjWECQQC3qMemXCmqp7lAaSqYy9Rk8HNVgEeDqJfhcIS4SrRH0DSExPE9yfhadaiC4IIYmmK5L*2V3dxIUI7KXbeO*ptz



---

spring:
  profiles: prepub
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uk11f20h4i65u9oo.mysql.rds.aliyuncs.com:3306/yunche_loan_biz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: yuncheadmin
      password: ycjinfu@2099
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
      initialSize: 8
      min-idle: 0
      max-active: 8
      test-on-borrow: true

  redis:
    host: 47.97.122.31
    port: 6381
    password: yunche@1234
    timeout: 3000
    lettuce:
      pool:
        max-active: 50
        max-idle: 30
        min-idle: 0
        max-wait: 10000

  mail:
    host: smtp.exmail.qq.com
    username: yanzheng@yunchejinrong.com
    password: Yunche@1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jtx:
    jtxServierIP: 120.26.205.193
    jtxUserName: asset
    jtxPassword: asset001
    jtxUrl: http://114.215.191.155:7013/assetApi/service
    jtxPort: 22

---

spring:
  profiles: pub
  datasource:
    druid:
      url: jdbc:mysql://rm-bp1uk11f20h4i65u9rw.mysql.rds.aliyuncs.com:3306/yunche_loan_biz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: yuncheadmin
      password: ycjinfu@2099
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 10000
      initialSize: 16
      minIdle: 16
      max-active: 30
      test-on-borrow: true

  redis:
    host: r-bp1b3d268c17de84.redis.rds.aliyuncs.com
    port: 6379
    password: Yunche2018
    timeout: 3000
    lettuce:
      pool:
        max-active: 1000
        max-idle: 500
        min-idle: 50
        max-wait: 5000

  mail:
    host: smtp.exmail.qq.com
    username: yanzheng@yunchejinrong.com
    password: Yunche@1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jtx:
    jtxServierIP: 120.26.205.193
    jtxUserName: asset
    jtxPassword: asset001
    jtxUrl: http://114.215.191.155:7013/assetApi/service
    jtxPort: 22

  finance:
     callBackUrl: http://www.yunchejinrong.com:8081/api/v1/loanorder/finance/remitInfo
     accountingVoucherHost: http://47.110.7.61:8012
     secondCarHost: http://47.97.122.31:8888
     paymentHost: http://47.110.7.61:8019